# to read the config for terminating authentication
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: kubedb-server-extension-server-authentication-reader
  namespace: kube-system
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: ${KUBEDB_SERVICE_ACCOUNT}
  namespace: ${KUBEDB_NAMESPACE}
---
# to delegate authentication and authorization
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kubedb-server-auth-delegator
  labels:
    app: kubedb
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: ${KUBEDB_SERVICE_ACCOUNT}
  namespace: ${KUBEDB_NAMESPACE}
---
# to let aggregated apiservers create admission reviews
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kubedb:server-requester
  labels:
    app: kubedb
rules:
- apiGroups: ['admission.kubedb.com']
  resources: ['*']
  verbs: ['create']
---
# to let the admission server read the secrets and pvc
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubedb:server
  labels:
    app: kubedb
rules:
- apiGroups: ["storage.k8s.io"]
  resources:
  - storageclasses
  verbs:
  - get
- apiGroups: ["kubedb.com"]
  resources:
  - dormantdatabases
  verbs:
  - get
- apiGroups: [""]
  resources:
  - secrets
  verbs:
  - get
---
# to let the admission server read the secrets and pvc
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubedb-server
  labels:
    app: kubedb
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: kubedb:server
subjects:
- kind: ServiceAccount
  name: ${KUBEDB_SERVICE_ACCOUNT}
  namespace: ${KUBEDB_NAMESPACE}
